### ISSUE TITLE
license - a bit more relaxing?

### ISSUE THREAD

**Issue by ulno** [kokoko3k/ssh-rdp#1]
Would it be possible that you relax the license at least to LGPL, that would allow us to use this in other projects? I can now not anymore use your ideas for working in virtual reality as most of my projects use permissive open source licenses allowing other developers using my software. If I would start using your software, all my projects using your software have to legally convert to GPLv3 (it's a viral license) as well as all software using my projects - this makes the GPLv3 extremely unattractive for other developers.

**Comment by kokoko3k** [comment]
I don't think what you say applies to scripts, but, i'm not a lawyer and i've no problem in switching.
Changed with: https://github.com/kokoko3k/ssh-rdp/commit/a9a7ff3a2544a374c56ca3cfa418d571e6e0b139
