### ISSUE TITLE
Ability to show cursor with X11 host and kmsgrab

### ISSUE THREAD

**Issue by parkerlreed** [kokoko3k/ssh-rdp#12]
Noticed using kmsgrab that the X11 host cursor becomes invisible, making using this a bit tougher.

Searching for a way to display this but not coming up with anything. Has this been explored before?

The cursor still functions you just can't see where it's at on the screen.

**Comment by parkerlreed** [comment]
Found this as a possible solution. Mentions kmsgrab not working with hardware cursors at all. https://github.com/andykitchen/swcursor

**Comment by parkerlreed** [comment]
That works fairly well. For anyone else on Plasma with Breeze Dark https://raw.githubusercontent.com/black7375/Breeze-Cursors-for-Windows/master/Sources/normal.png

**Comment by kokoko3k** [comment]
Beware, that using software cursors breaks page flipping, and it will lead to tearing artifacts if not using a compositor.

**Comment by kokoko3k** [comment]
Take a look at this:
https://github.com/swillner/highlight-pointer
it can be turned off via hotkey when not needed, so it would be useful for games that provide their own mouse cursors.
