### ISSUE TITLE
Add option to use libx264rgb

### ISSUE THREAD

**Issue by markg85** [kokoko3k/ssh-rdp#13]
Hi,

First of, thank you so much for all the work you've put into this! While i'm not using your script directly, i did take note of the flags you use for ffmpeg, ffplay and mpv to achieve the most snappy performance possible! That kind of information is surprisingly hard to find! Thank you :)

On to the suggestion. By default the software rendering option uses libx264 which - i think - default to yuv420b. This default is just fine for say gaming or video streaming but it's a bit lacking when you'd stream a desktop. For desktop streaming you'd want yuv444 or comparable as that keeps text sharp. You can try software encoding with the following flags changed:
`-c:v libx264rgb -profile:v high444 -pix_fmt bgr24`

The results looks, in my opinion, far better. This does come at a cost of increased bandwidth and potentially a minute latency bump. Although in my testing (a ryzen 4800U laptop CPU with build-in GPU), I didn't notice any latency change at all.

If you also don't notice a latency change then i'd go as far as suggesting to make this the default for desktop streaming when using software rendering.

**Comment by kokoko3k** [comment]
Hi there.
Indeed the text is far better, thank you for the hint!

I've added a new preset named cpurgb via https://github.com/kokoko3k/ssh-rdp/commit/cb740751c99cfbffc6247591488fe4e0b90fbeb3
