### ISSUE TITLE
touchpad gesture

### ISSUE THREAD

**Issue by jcosmao** [kokoko3k/ssh-rdp#21]
Hello,

Thanks for this tool, it's working really nicely !

I wonder if it would be possible to get touchpad gesture working (1/2/3 finger touch to emulate physical KeyPress events).
Currently i'm not able to get those input events forwarded to remote ssh. Only physical button press is handled.
Maybe it's more a question for netevent project, but i'm asking there in case i missed something.

Thx

**Comment by kokoko3k** [comment]
When doing the inputconfig part, have you tried to press the gesture you want to forward?

(unlikely, but still...) Maybe your touchpad is seen by the kernel as a different device when it comes to gestures?

Another guess is that there is an userspace tool on the client converting those gestures in keypresses; in which case such software should be installed server side.

**Comment by jcosmao** [comment]
> Another guess is that there is an userspace tool on the client converting those gestures in keypresses; in which case such software should be installed server side.

issue fixed, i was just missing xorg synaptic driver/conf on remote host..

```shell
 ❭ yay -Ss xf86-input-synaptics
extra/xf86-input-synaptics 1.9.2-1 (57.0 KiB 137.8 KiB) [xorg-drivers] (Installed)
    Synaptics driver for notebook touchpads


 ❭ cat /etc/X11/xorg.conf.d/50-synaptic.conf
Section "InputClass"
	Identifier "Force Clickpad Config"
	MatchDriver "synaptics"
	Option "ClickPad" "true"
		Option "EmulateMidButtonTime" "0"
		Option "SoftButtonAreas" "50% 0 82% 0 0 0 0 0"
		Option "SecondarySoftButtonAreas" "58% 0 0 15% 42% 58% 0 15%"
        Option "TapButton1" "1"
        Option "TapButton2" "3"
        Option "TapButton3" "2"
        Option "VertEdgeScroll" "off"
        Option "HorizEdgeScroll" "off"
        Option "VertTwoFingerScroll" "on"
        Option "HorizTwoFingerScroll" "on"
        Option "CircularScrolling" "on"
        Option "CircScrollTrigger" "2"
        Option "EmulateTwoFingerMinZ" "0"
        Option "PalmDetect" "1"
        Option "PalmMinWidth" "8"
        Option "PalmMinZ" "100"
EndSection

``` 

Thx !
