### ISSUE TITLE
[FEATURE-QUESTION] Remote connect from another network

### ISSUE THREAD

**Issue by DFran49** [kokoko3k/ssh-rdp#25]
Hi, first, I want to apologize if this is not the place for this question.

I need to know if I can connect to my home pc with my laptop when I'm in class for example, where I'm in another network.
Also, is there a problem if I use a host pc with amd graphics and cpu while I connect at it using a NVIDIA graphics card and an intel cpu?

Thank you for everything ^^

**Comment by kokoko3k** [comment]
ssh-rdp carries everything over ssh.
As long as you can open an ssh connection to the server, it should work.

**Comment by DFran49** [comment]
Thank you for answering so quickly, you are a life saver. My setup was focused on remote gaming mainly when I used windows, but when I switched to arch, it was a pain to find something.
Have a good day :3

**Comment by kokoko3k** [comment]
You're welcome; you can mix different local and remote gpu vendors/models.
