### ISSUE TITLE
[Question] mouse wheel events not forwarded?

### ISSUE THREAD

**Issue by xenogenesi** [kokoko3k/ssh-rdp#26]
I've been using ssh-rdp for a while now and it works great, up until now I've only used the touchscreen as input, recently I had to use a mouse, is it just me or are the wheel events not forwarded?

**Comment by kokoko3k** [comment]
Forwarding happens at very low level and there should be nothing special about wheel events.

FWIW, wheel works fine here.

As a shoot in the dark, try to redo the input config and when it asks you to forward another device, use your wheel and see what happens.

**Comment by xenogenesi** [comment]
Thank you for your quick answer!

I just tried to recreate the events, if I use the wheel as a button it works, but if I use it to scroll it doesn't work.

Thanks for confirming that it must work, probably a problem with the system I'm using it with, I'll check again!
