### ISSUE TITLE
PipeWire

### ISSUE THREAD

**Issue by MichaelArthurLong** [kokoko3k/ssh-rdp#8]
Any reason we're using pacmd by default instead of pactl?

PipeWire doesn't have pacmd so we're stuck to using pactl.

**Comment by kokoko3k** [comment]
Not really, i guess.
I'm still with pulse and  didn't know pacmd was missing from pipwwire.
How can we get the same/equivalent parsable output out of pactl? 
I can check in a couple of days.

**Comment by MichaelArthurLong** [comment]
>  How can we get the same/equivalent parsable output out of pactl?

I'm a bit confused. Didn't you already wrote that in a long time ago? That's what #7 fixed.
I've tried using it and it seems to work fine.

**Comment by kokoko3k** [comment]
And it is probably right.
I'll check in a couple of days, because all I have now is an android phone.
I'll have to make sure it works for multiple audio output capture too.
